x2

diff --git a/.github/workflows/python-greetings.yml b/.github/workflows/python-greetings.yml
--- a/.github/workflows/python-greetings.yml
+++ b/.github/workflows/python-greetings.yml
@@ -42,9 +42,17 @@ jobs:
         run: pm2 start app.py --name greetings-app-dev -- --port 7001
         working-directory: ./python-greetings
 
-      - name: Display PM2 logs
-        run: pm2 logs greetings-app-dev --lines 50
-        working-directory: ./python-greetings
+      # - name: Display PM2 logs
+      #   run: pm2 logs greetings-app-dev --lines 50
+      #   working-directory: ./python-greetings
+      - name: Check if port 7001 is in use
+        run: |
+          if sudo netstat -tuln | grep ':7001' > /dev/null; then
+            echo "Something is running on port 7001."
+            exit 1  # Optional: Fail the job if something is running on the port
+          else
+            echo "Port 7001 is free."
+          fi
 
       - name: Deploy to Development Environment
         run: echo "Deploying to dev environment"
